.. _about-section:

About
=====

The **nirfsa** module provides a Python API for NI-RFSA. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
**nirfsa** supports all the Operating Systems supported by NI-RFSA.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions of CPython.

NI created and supports **nirfsa**.

