coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # TODO(texasaggie97) - target lowered when adding system test coverage. Raise as coverage rises.
        # TODO(texasaggie97) - update target when files other than _library.py removed from coverage report
        target: 70%
        threshhold: 5
    patch:
      default:
        target: 70%
        threshhold: 5


