coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshhold: 5
    patch:
      default:
        target: 70%
        threshhold: 5


