coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # TODO(texasaggie97) - target lowered when adding system test coverage. Raise as coverage rises.
        target: 85%
        threshhold: 5
    patch:
      default:
        target: 70%
        threshhold: 5

