variables:
- name: clone_depth
  value: 10 
- name: tox_parallel_threads
  value: 2

parameters:
  module_name: ""
  os_name: ""

jobs:
- job: ${{ parameters.module_name }}_system_tests_${{ parameters.os_name }}
  workspace:
    clean: all
  steps:
    - checkout: self  
      clean: true
      fetchDepth: ${{ variables.clone_depth }}
    - script: |
        cd generated
        mkdir unit
        mkdir kibana
        cd ${{ parameters.module_name }}
        python -m tox -c tox-system_tests.ini --parallel ${{ variables.tox_parallel_threads }} --parallel-live
      displayName: ${{ parameters.module_name }} system tests ${{ parameters.os_name }} 
      env:
        TOX_PARALLEL_NO_SPINNER: 1
