parameters:
  module_name: ""
  os_name: ""
  clone_depth: 10


jobs:
- job: ${{ parameters.module_name }}
  workspace:
    clean: all
  steps:
    - checkout: self  
      clean: true
      fetchDepth: ${{ parameters.clone_depth }}
    - script: |
        cd generated
        mkdir junit
        mkdir kibana
        cd ${{ parameters.module_name }}
        python -m tox -c tox-system_tests.ini
      displayName: Run system tests
      env:
        TOX_PARALLEL_NO_SPINNER: 1

