parameters:
  module_name: ""
  os_name: ""
  clone_depth: 10
  tox_parallel_threads: 2


jobs:
- job: ${{ parameters.module_name }}_system_tests_${{ parameters.os_name }}
  workspace:
    clean: all
  steps:
    - checkout: self  
      clean: true
      fetchDepth: ${{ parameters.clone_depth }}
    - script: |
        cd generated
        mkdir junit
        mkdir kibana
        cd ${{ parameters.module_name }}
        python -m tox -c tox-system_tests.ini --parallel ${{ parameters.tox_parallel_threads }} --parallel-live
      displayName: ${{ parameters.module_name }} system tests ${{ parameters.os_name }} 
      env:
        TOX_PARALLEL_NO_SPINNER: 1
