name: "Run system tests"
description: "Run system tests for the specified module"
inputs:
  module_name:
    description: "module name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - run: |
        echo "Hello ${{ inputs.module_name }}"
        whoami
        echo "$PATH"
        type -a python
        which python
        ls -l /usr/bin/python
        ls -l /usr/bin/python*
        ls -l /usr/local/bin/python*
      shell: bash
    - run: |
        cd generated
        mkdir junit
        mkdir kibana
        cd ${{ inputs.module_name }}
        python -m tox -c tox-system_tests.ini
      shell: bash
