# Run system tests for the specified module

parameters:
  module_name: ""
  clone_depth: 1


jobs:
- job: ${{ parameters.module_name }}
  workspace:
    clean: all
  steps:
    - checkout: self  
      clean: true
      fetchDepth: ${{ parameters.clone_depth }}
    - script: |
        echo "cd generated"
        cd generated
        echo "mkdir junit"
        mkdir junit
        echo "mkdir kibana"
        mkdir kibana
        echo "cd ${{ parameters.module_name }}"
        cd ${{ parameters.module_name }}
        pyenv local 3.6.8 3.7.9 3.8.9 3.9.4
        echo "test"
        python -m tox -c tox-system_tests.ini
      displayName: Run system tests
      env:
        TOX_PARALLEL_NO_SPINNER: 1

