.. _about-section:

About
=====

The **nise** package provides a Python API for NI Switch Executive. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
nise supports all the Operating Systems supported by NI Switch Executive.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions.

