.. _about-section:

About
=====

The **nidmm** package provides a Python API for NI-DMM. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
nidmm supports all the Operating Systems supported by NI-DMM.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions.

