.. _about-section:

About
=====

The **nimodinst** module provides a Python API for NI-ModInst. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
**nimodinst** supports all the Operating Systems supported by NI-ModInst.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions of CPython.

