.. _about-section:

About
=====

The **nitclk** module provides a Python API for NI-TClk. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
nitclk supports all the Operating Systems supported by NI-TClk.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions.

