
NI-TClk Python API Status
-------------------------

+-------------------------------+-----------------------+
| NI-TClk (nitclk)              |                       |
+===============================+=======================+
| Driver Version Tested Against | 2023 Q2               |
+-------------------------------+-----------------------+
| PyPI Version                  | |nitclkLatestVersion| |
+-------------------------------+-----------------------+
| Supported Python Version      | |nitclkPythonVersion| |
+-------------------------------+-----------------------+
| Documentation                 | |nitclkDocs|          |
+-------------------------------+-----------------------+
| Open Issues                   | |nitclkOpenIssues|    |
+-------------------------------+-----------------------+
| Open Pull Requests            | |nitclkOpenPRs|       |
+-------------------------------+-----------------------+


.. |nitclkLatestVersion| image:: http://img.shields.io/pypi/v/nitclk.svg
    :alt: Latest NI-TClk Version
    :target: http://pypi.python.org/pypi/nitclk


.. |nitclkPythonVersion| image:: http://img.shields.io/pypi/pyversions/nitclk.svg
    :alt: NI-TClk supported Python versions
    :target: http://pypi.python.org/pypi/nitclk


.. |nitclkDocs| image:: https://readthedocs.org/projects/nitclk/badge/?version=latest
    :alt: NI-TClk Python API Documentation Status
    :target: https://nitclk.readthedocs.io/en/latest


.. |nitclkOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nitclk.svg
    :alt: Open Issues + Pull Requests for NI-TClk
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anitclk


.. |nitclkOpenPRs| image:: https://img.shields.io/github/issues-pr/ni/nimi-python/nitclk.svg
    :alt: Pull Requests for NI-TClk
    :target: https://github.com/ni/nimi-python/pulls?q=is%3Aopen+is%3Aissue+label%3Anitclk


