attributes = {
    'DEVICE_NAME':
    {
        'id':0,
        'type':'ViString',
        'enum':None,
        'access':'read'
    },
    'DEVICE_MODEL':
    {
        'id':1,
        'type':'ViString',
        'enum':None,
        'access':'read'
    },
    'SERIAL_NUMBER':
    {
        'id':2,
        'type':'ViString',
        'enum':None,
        'access':'read'
    },
    'SLOT_NUMBER':
    {
        'id':10,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
    'CHASSIS_NUMBER':
    {
        'id':11,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
    'BUS_NUMBER':
    {
        'id':12,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
    'SOCKET_NUMBER':
    {
        'id':13,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
    'PCIEXPRESS_LINK_WIDTH':
    {
        'id':17,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
    'MAX_PCIEXPRESS_LINK_WIDTH':
    {
        'id':18,
        'type':'ViInt32',
        'enum':None,
        'access':'read'
    },
}


