functions = [
    {   'name': 'OpenInstalledDevicesSession',
        'codegen_method': 'public',
        'parameters': [
            {'direction': 'in', 'enum': None,
             'name': 'driver',
             'type': 'ViConstString'},
            {'direction': 'out', 'enum': None,
             'name': 'session',
             'type': 'ViSession'},
            {'direction': 'out', 'enum': None,
             'name': 'item_count',
             'type': 'ViInt32'},
        ],
        'returns': 'ViStatus'},
    {   'name': 'GetInstalledDeviceAttributeViString',
        'codegen_method': 'private',
        'parameters': [
            {'direction': 'in', 'enum': None,
             'name': 'vi',
             'type': 'ViSession'},
            {'direction': 'in', 'enum': None,
             'name': 'index',
             'type': 'ViInt32'},
            {'direction': 'in', 'enum': None,
             'name': 'attributeID',
             'type': 'ViInt32'},
            {'direction': 'in', 'enum': None,
             'name': 'attributeValueBufferSize',
             'type': 'ViInt32'},
            {'direction': 'in', 'enum': None,
             'name': 'attributeValue',
             'type': 'ViChar'},
        ],
        'returns': 'ViStatus'},
    {   'name': 'GetInstalledDeviceAttributeViInt32',
        'codegen_method': 'private',
        'parameters': [
            {'direction': 'in', 'enum': None,
             'name': 'vi',
             'type': 'ViSession'},
            {'direction': 'in', 'enum': None,
             'name': 'index',
             'type': 'ViInt32'},
            {'direction': 'in', 'enum': None,
             'name': 'attributeID',
             'type': 'ViInt32'},
            {'direction': 'out', 'enum': None,
             'name': 'attributeValue',
             'type': 'ViInt32'},
        ],
        'returns': 'ViStatus'},
    {   'name': 'CloseInstalledDevicesSession',
        'codegen_method': 'public',
        'parameters': [
            {'direction': 'in', 'enum': None,
             'name': 'vi', 'type': 'ViSession'},
        ],
        'returns': 'ViStatus'},
    {   'name': 'GetExtendedErrorInfo',
        'codegen_method': 'public',
        'parameters': [
            {'direction': 'in', 'enum': None,
             'name': 'errorInfoBufferSize', 'type': 'ViInt32'},
            {'direction': 'in', 'enum': None,
             'name': 'errorInfo',
             'type': 'ViChar'},
        ],
        'returns': 'ViStatus'},
]


