functions = [   {   'name': 'init',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'is_buffer': True,
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'IDQuery',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reset', 'type': 'ViBoolean'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'InitWithOptions',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'is_buffer': True,
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'IDQuery',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resetDevice',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'optionsString',
                                       'is_buffer': True,
                                       'type': 'ViString'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'close',
                    'codegen_method': 'private',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetError',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'errorCode',
                                       'type': 'ViStatus'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'description',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetErrorMessage',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'errorCode',
                                       'type': 'ViStatus'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'errMessage',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'ClearError',
                    'codegen_method': 'private',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'reset',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'self_test',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'selfTestResult',
                                       'type': 'ViInt16'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'selfTestMessage',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'SelfCal',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'revision_query',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'driverRev',
                                       'is_buffer': True,
                                       'type': 'ViChar'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'instrRev',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'InvalidateAllAttributes',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'ResetWithDefaults',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'Disable',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetMeasurementPeriod',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'period', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureTrigger',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'TriggerSource',
                                       'name': 'trigSource',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'triggerDelay',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'Read',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reading',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'Fetch',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reading',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'Abort',
                    'codegen_method': 'private',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'Initiate',
                    'codegen_method': 'private',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'IsOverRange',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measurementValue',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'isOverRange',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'IsUnderRange',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measurementValue',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'isUnderRange',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureACBandwidth',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'minFreq', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxFreq',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureFrequencyVoltageRange',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequencyVoltageRange',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureMeasCompleteDest',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'MeasurementCompleteDest',
                                       'name': 'destination',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureMultiPoint',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'triggerCount',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'sampleCount',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': 'SampleTrigger',
                                       'name': 'sampleTrigger',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'sampleInterval',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ReadMultiPoint',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'readingArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPts',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'FetchMultiPoint',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'readingArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPts',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureTriggerSlope',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Slope',
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'SendSoftwareTrigger',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetApertureTimeInfo',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'apertureTime',
                                       'type': 'ViReal64'},
                                      {'direction': 'out',
                                       'enum': 'ApertureTimeUnits',
                                       'name': 'apertureTimeUnits',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAutoRangeValue',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'autoRangeValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureAutoZeroMode',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'EnabledSetting',
                                       'name': 'autoZeroMode',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigurePowerLineFrequency',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequency',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureMeasurementDigits',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Function',
                                       'name': 'measFunction',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resolutionDigits',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureMeasurementAbsolute',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Function',
                                       'name': 'measFunction',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resolutionAbsolute',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureMeasCompleteSlope',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Slope',
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureSampleTriggerSlope',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Slope',
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ReadStatus',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'acqBacklog',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': 'AcquisitionStatus',
                                       'name': 'acqDone', 'type': 'ViInt16'}],
                    'returns': 'ViStatus'},
                {   'name': 'Control',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None, # TODO(marcoskirsch): About to be obsoleted and replaced with commit.
                                       'name': 'action', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureADCCalibration',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'EnabledSetting',
                                       'name': 'adcGainComp', # TODO(marcoskirsch): bad param name?
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureOffsetCompOhms',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'EnabledSetting',
                                       'name': 'offsetCompOhms',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureCurrentSource',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'CurrentSource',
                                       'name': 'diodeCurrentSrc',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureCableCompType',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'CableCompensationType',
                                       'name': 'typeOfCompensation',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'PerformOpenCableComp',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'conductance',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'susceptance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'PerformShortCableComp',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reactance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureOpenCableCompValues',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'conductance',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'susceptance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureShortCableCompValues',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reactance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'LockSession',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'callerHasLock',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'UnlockSession',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'callerHasLock',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureWaveformAcquisition',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'Function',
                                       'name': 'function', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'rate', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureWaveformCoupling',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'WaveformCouplingMode',
                                       'name': 'coupling',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'FetchWaveform',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ReadWaveform',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAttributeViInt32',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetAttributeViInt32',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'CheckAttributeViInt32',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAttributeViReal64',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetAttributeViReal64',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'CheckAttributeViReal64',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAttributeViString',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufSize', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value',
                                       'is_buffer': True,
                                       'type': 'ViString'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetAttributeViString',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value',
                                       'is_buffer': True,
                                       'type': 'ViString'}],
                    'returns': 'ViStatus'},
                {   'name': 'CheckAttributeViString',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAttributeViSession',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetAttributeViSession',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'CheckAttributeViSession',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetAttributeViBoolean',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetAttributeViBoolean',
                    'codegen_method': 'private',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'CheckAttributeViBoolean',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'is_buffer': True,
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetNextCoercionRecord',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'record',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetNextInterchangeWarning',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'warnString',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'ResetInterchangeCheck',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'ClearInterchangeWarnings',
                    'codegen_method': 'public',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': '4022Control',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'is_buffer': True,
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'configuration',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetChannelName',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'index', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'name',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'InitExtCal',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'is_buffer': True,
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'password',
                                       'is_buffer': True,
                                       'type': 'ViChar'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi',
                                       'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'CloseExtCal',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'action', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustLinearization',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustGain',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustOffset',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustMisc',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'type', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustLC',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'type', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'CalAdjustACFilter',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequency',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'RestoreLastExtCalConstants',
                    'codegen_method': 'no',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetCalPassword',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'oldPassword',
                                       'is_buffer': True,
                                       'type': 'ViChar'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'newPassword',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetExtCalRecommendedInterval',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'months', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'SetCalUserDefinedInfo',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'info',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetCalUserDefinedInfoMaxSize',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'infoSize',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetCalUserDefinedInfo',
                    'codegen_method': 'no',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'info',
                                       'is_buffer': True,
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetSelfCalSupported',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'selfCalSupported',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetCalDateAndTime',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'month', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'day', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'year', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'hour', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'minute', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetCalCount',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'count', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetLastCalTemp',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'temperature',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'GetDevTemp',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reserved',
                                       'is_buffer': True,
                                       'type': 'ViString'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'temperature',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureTransducerType',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'TemperatureTransducerType',
                                       'name': 'transducerType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureThermocouple',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'thermocoupleType',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'refJunctionType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureFixedRefJunction',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'fixedRefJunction',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureRTDType',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'rtdType', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureRTDCustom',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'a', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'b', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'c', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureThermistorType',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': 'TemperatureThermistorType',
                                       'name': 'thermistorType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'ConfigureThermistorCustom',
                    'codegen_method': 'public',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'a', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'b', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'c', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'}]


