
NI-Sync Python API Status
-------------------------

+-------------------------------+-----------------------+
| NI-Sync (nisync)              |                       |
+===============================+=======================+
| Driver Version Tested Against | 18.1.0                |
+-------------------------------+-----------------------+
| Driver API Version            | 20.0.0d0              |
+-------------------------------+-----------------------+
| PyPI Version                  | |nisyncLatestVersion| |
+-------------------------------+-----------------------+
| Supported Python Version      | |nisyncPythonVersion| |
+-------------------------------+-----------------------+
| Open Issues                   | |nisyncOpenIssues|    |
+-------------------------------+-----------------------+
| Open Pull Requests            | |nisyncOpenPRs|       |
+-------------------------------+-----------------------+


.. |nisyncLatestVersion| image:: http://img.shields.io/pypi/v/nisync.svg
    :alt: Latest NI-Sync Version
    :target: http://pypi.python.org/pypi/nisync


.. |nisyncPythonVersion| image:: http://img.shields.io/pypi/pyversions/nisync.svg
    :alt: NI-Sync supported Python versions
    :target: http://pypi.python.org/pypi/nisync


.. |nisyncOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nisync.svg
    :alt: Open Issues + Pull Requests for NI-Sync
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anisync


.. |nisyncOpenPRs| image:: https://img.shields.io/github/issues-pr/ni/nimi-python/nisync.svg
    :alt: Pull Requests for NI-Sync
    :target: https://github.com/ni/nimi-python/pulls?q=is%3Aopen+is%3Aissue+label%3Anisync


