# TODO(marcoskirsch): Need to fill in enum information for those parameters that require it.
functions = [   {   'name': 'niDMM_init',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'IDQuery',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reset', 'type': 'ViBoolean'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_InitWithOptions',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'IDQuery',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resetDevice',
                                       'type': 'ViBoolean'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'optionsString',
                                       'type': 'ViString'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_close',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetError',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'errorCode',
                                       'type': 'ViStatus'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'description',
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetErrorMessage',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'errorCode',
                                       'type': 'ViStatus'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'errMessage',
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ClearError',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_reset',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_self_test',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'selfTestResult',
                                       'type': 'ViInt16'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'selfTestMessage',
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SelfCal',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_revision_query',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'driverRev', 'type': 'ViChar'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'instrRev', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_InvalidateAllAttributes',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ResetWithDefaults',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Disable',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetMeasurementPeriod',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'period', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureTrigger',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'trigSource',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'triggerDelay',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Read',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reading',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Fetch',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reading',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Abort',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Initiate',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_IsOverRange',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measurementValue',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'isOverRange',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_IsUnderRange',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measurementValue',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'isUnderRange',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureACBandwidth',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'minFreq', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxFreq',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureFrequencyVoltageRange',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequencyVoltageRange',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureMeasCompleteDest',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'destination',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureMultiPoint',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'triggerCount',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'sampleCount',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'sampleTrigger',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'sampleInterval',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ReadMultiPoint',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'readingArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPts',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_FetchMultiPoint',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'readingArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPts',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureTriggerSlope',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SendSoftwareTrigger',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetApertureTimeInfo',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'apertureTime',
                                       'type': 'ViReal64'},
                                      {'direction': 'out',
                                       'enum': 'ApertureTimeUnits',
                                       'name': 'apertureTimeUnits',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAutoRangeValue',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'autoRangeValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureAutoZeroMode',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'autoZeroMode',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigurePowerLineFrequency',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequency',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureMeasurementDigits',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measFunction',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resolutionDigits',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureMeasurementAbsolute',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'measFunction',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resolutionAbsolute',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureMeasCompleteSlope',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureSampleTriggerSlope',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'polarity',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ReadStatus',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'acqBacklog',
                                       'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'acqDone', 'type': 'ViInt16'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_Control',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'action', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureADCCalibration',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'adcGainComp',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureOffsetCompOhms',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'offsetCompOhms',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureCurrentSource',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'diodeCurrentSrc',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureCableCompType',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'typeOfCompensation',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_PerformOpenCableComp',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'conductance',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'susceptance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_PerformShortCableComp',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'reactance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureOpenCableCompValues',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'conductance',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'susceptance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureShortCableCompValues',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reactance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_LockSession',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'callerHasLock',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_UnlockSession',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'callerHasLock',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureWaveformAcquisition',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'function', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'rate', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureWaveformCoupling',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'coupling',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_FetchWaveform',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ReadWaveform',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'maxTime', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'arraySize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'waveformArray',
                                       'type': 'ViReal64'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'actualPoints',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAttributeViInt32',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetAttributeViInt32',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CheckAttributeViInt32',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAttributeViReal64',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetAttributeViReal64',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CheckAttributeViReal64',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAttributeViString',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufSize', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetAttributeViString',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CheckAttributeViString',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAttributeViSession',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetAttributeViSession',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CheckAttributeViSession',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetAttributeViBoolean',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetAttributeViBoolean',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CheckAttributeViBoolean',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'channelName',
                                       'type': 'ViConstString'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'attributeId',
                                       'type': 'ViAttr'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'value', 'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetNextCoercionRecord',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'record', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetNextInterchangeWarning',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'warnString',
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ResetInterchangeCheck',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ClearInterchangeWarnings',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_4022Control',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'configuration',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetChannelName',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'index', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'name', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_InitExtCal',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'resourceName',
                                       'type': 'ViRsrc'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'password', 'type': 'ViChar'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'newVi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CloseExtCal',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'action', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustLinearization',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustGain',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustOffset',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'inputR', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustMisc',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'type', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustLC',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'type', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_CalAdjustACFilter',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'mode', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'range', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'frequency',
                                       'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'expectedValue',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_RestoreLastExtCalConstants',
                    'parameters': [{'direction': 'in', 'enum': None,
                                    'name': 'vi', 'type': 'ViSession'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetCalPassword',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'oldPassword',
                                       'type': 'ViChar'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'newPassword',
                                       'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetExtCalRecommendedInterval',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'months', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_SetCalUserDefinedInfo',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'info', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetCalUserDefinedInfoMaxSize',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'infoSize',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetCalUserDefinedInfo',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'bufferSize',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'info', 'type': 'ViChar'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetSelfCalSupported',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'selfCalSupported',
                                       'type': 'ViBoolean'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetCalDateAndTime',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'month', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'day', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'year', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'hour', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'minute', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetCalCount',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'count', 'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetLastCalTemp',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'calType', 'type': 'ViInt32'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'temperature',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_GetDevTemp',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'reserved',
                                       'type': 'ViString'},
                                      {'direction': 'out', 'enum': None,
                                       'name': 'temperature',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureTransducerType',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'transducerType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureThermocouple',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'thermocoupleType',
                                       'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'refJunctionType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureFixedRefJunction',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'fixedRefJunction',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureRTDType',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'rtdType', 'type': 'ViInt32'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'resistance',
                                       'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureRTDCustom',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'a', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'b', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'c', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureThermistorType',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'thermistorType',
                                       'type': 'ViInt32'}],
                    'returns': 'ViStatus'},
                {   'name': 'niDMM_ConfigureThermistorCustom',
                    'parameters': [   {'direction': 'in', 'enum': None,
                                       'name': 'vi', 'type': 'ViSession'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'a', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'b', 'type': 'ViReal64'},
                                      {'direction': 'in', 'enum': None,
                                       'name': 'c', 'type': 'ViReal64'}],
                    'returns': 'ViStatus'}]


