.. _about-section:

About
=====

The **niswitch** package provides a Python API for NI-SWITCH. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
niswitch supports all the Operating Systems supported by NI-SWITCH.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions.

