
.. _nirfsg_installation-section:

Installation
------------

As a prerequisite to using the **nirfsg** module, you must install the NI-RFSG runtime on your system. Visit `ni.com/downloads <http://www.ni.com/downloads/>`_ to download the driver runtime for your devices.

The nimi-python modules (i.e. for **NI-RFSG**) can be installed with `pip <http://pypi.python.org/pypi/pip>`_::

  $ python -m pip install nirfsg


