
NI-RFSG Python API Status
-------------------------

+-------------------------------+-----------------------+
| NI-RFSG (nirfsg)              |                       |
+===============================+=======================+
| Driver Version Tested Against | 2023 Q1.1             |
+-------------------------------+-----------------------+
| PyPI Version                  | |nirfsgLatestVersion| |
+-------------------------------+-----------------------+
| Supported Python Version      | |nirfsgPythonVersion| |
+-------------------------------+-----------------------+
| Documentation                 | |nirfsgDocs|          |
+-------------------------------+-----------------------+
| Open Issues                   | |nirfsgOpenIssues|    |
+-------------------------------+-----------------------+
| Open Pull Requests            | |nirfsgOpenPRs|       |
+-------------------------------+-----------------------+


.. |nirfsgLatestVersion| image:: http://img.shields.io/pypi/v/nirfsg.svg
    :alt: Latest NI-RFSG Version
    :target: http://pypi.python.org/pypi/nirfsg


.. |nirfsgPythonVersion| image:: http://img.shields.io/pypi/pyversions/nirfsg.svg
    :alt: NI-RFSG supported Python versions
    :target: http://pypi.python.org/pypi/nirfsg


.. |nirfsgDocs| image:: https://readthedocs.org/projects/nirfsg/badge/?version=latest
    :alt: NI-RFSG Python API Documentation Status
    :target: https://nirfsg.readthedocs.io/en/latest


.. |nirfsgOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nirfsg.svg
    :alt: Open Issues + Pull Requests for NI-RFSG
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anirfsg


.. |nirfsgOpenPRs| image:: https://img.shields.io/github/issues-pr/ni/nimi-python/nirfsg.svg
    :alt: Pull Requests for NI-RFSG
    :target: https://github.com/ni/nimi-python/pulls?q=is%3Aopen+is%3Aissue+label%3Anirfsg


