.. _about-section:

About
=====

The **niscope** module provides a Python API for NI-SCOPE. The code is maintained in the Open Source repository for `nimi-python <https://github.com/ni/nimi-python>`_.

Support Policy
--------------
**niscope** supports all the Operating Systems supported by NI-SCOPE.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions of CPython.

