# These dictionaries are merged with the extracted function metadata at build time.
# Changes to the metadata should be made here, because functions.py is generated thus any changes get overwritten.

functions_override_metadata = {
    # TODO(olsl21): Temporarily disable the new functions (#1715), they will be re-enabled in
    #  subsequent smaller PRs
    "FetchMultipleLCR": {"codegen_method": "no"},
    "MeasureMultipleLCR": {"codegen_method": "no"}
}

functions_additional_create_advanced_sequence = {
    'FancyCreateAdvancedSequence': {
        'codegen_method': 'python-only',
        'returns': 'ViStatus',
        'python_name': 'create_advanced_sequence',
        'method_templates': [
            { 'session_filename': 'fancy_advanced_sequence', 'documentation_filename': 'default_method', 'method_python_name_suffix': '', },
        ],
        'parameters': [
            {
                'direction': 'in',
                'name': 'vi',
                'type': 'ViSession',
                'documentation': {
                    'description': 'Identifies a particular instrument session. **vi** is obtained from the niDCPower_InitExtCal or niDCPower_InitializeWithChannels function.',
                },
            },
            {
                'direction': 'in',
                'name': 'channelName',
                'type': 'ViConstString'
            },
            {
                'direction': 'in',
                'name': 'SequenceName',
                'type': 'ViString',
                'documentation': {
                    'description': 'Specifies the name of the sequence to create.'
                },
            },
            {
                'direction': 'in',
                'name': 'PropertyNames',
                'type': 'ViString[]',
                'documentation': {
                    'description': 'Specifies the names of the properties you reconfigure per step in the advanced sequence. The following table lists which properties can be configured in an advanced sequence for each NI-DCPower device that supports advanced sequencing. A Yes indicates that the attribute can be configured in advanced sequencing. An No indicates that the attribute cannot be configured in advanced sequencing.',
                    'table_body': [
                        [
                            'NIDCPOWER_ATTR_DC_NOISE_REJECTION',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'No',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_APERTURE_TIME',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_MEASURE_RECORD_LENGTH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_SENSE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_OVP_ENABLED',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_OVP_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_DELAY',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_OFF_TIME',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_ON_TIME',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_SOURCE_DELAY',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_COMPENSATION_FREQUENCY',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_GAIN_BANDWIDTH',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_POLE_ZERO_RATIO',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_COMPENSATION_FREQUENCY',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_GAIN_BANDWIDTH',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_POLE_ZERO_RATIO',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LEVEL_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LIMIT_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_CURRENT_LIMIT_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_VOLTAGE_LEVEL_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_OUTPUT_ENABLED',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_OUTPUT_FUNCTION',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ],
                        [
                            'NIDCPOWER_ATTR_OUTPUT_RESISTANCE',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No',
                            'Yes',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LEVEL_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LIMIT_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_CURRENT_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_BIAS_VOLTAGE_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_HIGH',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_LOW',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_CURRENT_LIMIT_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LEVEL',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_PULSE_VOLTAGE_LEVEL_RANGE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'No',
                            'No',
                            'No'
                        ],
                        [
                            'NIDCPOWER_ATTR_TRANSIENT_RESPONSE',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes',
                            'Yes'
                        ]
                    ],
                    'table_header': [
                        'Attribute',
                        'PXIe-4135',
                        'PXIe-4136',
                        'PXIe-4137',
                        'PXIe-4138',
                        'PXIe-4139',
                        'PXIe-4140/4142/4144',
                        'PXIe-4141/4143/4145',
                        'PXIe-4162/4163'
                    ]
                },
            },
            {
                'direction': 'in',
                'name': 'setAsActiveSequence',
                'type': 'ViBoolean',
                'default_value': True,
                'documentation': { 'description': 'Specifies that this current sequence is active.', },
            },
        ],
        'documentation':
        {
            'description': '\nCreates an empty advanced sequence. Call the\nniDCPower_CreateAdvancedSequenceStepWithChannels function to add steps to the\nactive advanced sequence.\n\nYou can create multiple advanced sequences in a session.\n\n**Support for this function**\n\nYou must set the source mode to Sequence to use this function.\n\nUsing the niDCPower_SetSequence function with Advanced Sequence\nfunctions is unsupported.\n\nUse this function in the Uncommitted or Committed programming states.\nRefer to the `Programming\nStates <REPLACE_DRIVER_SPECIFIC_URL_1(programmingstates)>`__ topic in\nthe *NI DC Power Supplies and SMUs Help* for more information about\nNI-DCPower programming states.\n\n**Related Topics**:\n\n`Advanced Sequence\nMode <REPLACE_DRIVER_SPECIFIC_URL_1(advancedsequencemode)>`__\n\n`Programming\nStates <REPLACE_DRIVER_SPECIFIC_URL_1(programmingstates)>`__\n\nniDCPower_CreateAdvancedSequenceStepWithChannels\n',
            'note': "\nThis function is not supported on all devices. Refer to `Supported\nFunctions by\nDevice <REPLACE_DRIVER_SPECIFIC_URL_2(nidcpowercref.chm',%20'supportedfunctions)>`__\nfor more information about supported devices.\n"
        },
    },
}
