name: "Run system tests"
description: "Run system tests for the specified module"
inputs:
  module_name:
    description: "module name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        cd generated        
        mkdir junit
        cd ${{ inputs.module_name }}
        python -m tox -c tox-system_tests.ini
      shell: powershell