.. _about-section:

About
=====

This package, which is maintained in the `**nimi-python** repository <https://github.com/ni/nimi-python>`_, provides a Python API for the associated driver.

Support Policy
--------------
This package supports all the Operating Systems supported by the underlying driver.

It follows `Python Software Foundation <https://devguide.python.org/#status-of-python-branches>`_ support policy for different versions. At
this time this includes Python 3.8 and above using CPython.

