.. _installation-section:

Installation
============

Driver specific installation instructions can be found on Read The Docs:

* `nidcpower <http://nimi-python.readthedocs.io/en/master/nidcpower.html#installation>`_
* `nidigital <http://nimi-python.readthedocs.io/en/master/nidigital.html#installation>`_
* `nidmm <http://nimi-python.readthedocs.io/en/master/nidmm.html#installation>`_
* `nifgen <http://nimi-python.readthedocs.io/en/master/nifgen.html#installation>`_
* `nimodinst <http://nimi-python.readthedocs.io/en/master/nimodinst.html#installation>`_
* `niscope <http://nimi-python.readthedocs.io/en/master/niscope.html#installation>`_
* `nise <http://nimi-python.readthedocs.io/en/master/nise.html#installation>`_
* `niswitch <http://nimi-python.readthedocs.io/en/master/niswitch.html#installation>`_
* `nitclk <http://nimi-python.readthedocs.io/en/master/nitclk.html#installation>`_


