.. _installation-section:

Installation
============

Driver specific installation instructions can be found on **Read the Docs**:

* `nidcpower <https://nidcpower.readthedocs.io/en/latest/nidcpower.html#installation>`_
* `nidigital <https://nidigital.readthedocs.io/en/latest/nidigital.html#installation>`_
* `nidmm <https://nidmm.readthedocs.io/en/latest/nidmm.html#installation>`_
* `nifgen <https://nifgen.readthedocs.io/en/latest/nifgen.html#installation>`_
* `nimodinst <https://nimodinst.readthedocs.io/en/latest/nimodinst.html#installation>`_
* `niscope <https://niscope.readthedocs.io/en/latest/niscope.html#installation>`_
* `nise <https://nise.readthedocs.io/en/latest/nise.html#installation>`_
* `niswitch <https://niswitch.readthedocs.io/en/latest/niswitch.html#installation>`_
* `nitclk <https://nitclk.readthedocs.io/en/latest/nitclk.html#installation>`_


