.. _intro-section:

Intro
=====

**nimi-python** is a collection of Python modules that provide an interface to the underlying NI driver. Currently, the following drivers are supported:

* NI-DCPower (Python module: nidcpower)
* NI-DMM (Python module: nidmm)
* NI-FGEN (Python module: nifgen)
* NI-SCOPE (Python module: niscope)
* NI-SWITCH (Python module: niswitch)
* NI Switch Executive (Python module: nise)
* NI-ModInst (Python module: nimodinst)
* NI-TClk (Python module: nitclk)

**nimi-python** supports all the Operating Systems supported by the underlying driver.

**nimi-python** supports Python 2.7, 3.4 and later using CPython or PyPy.

