:orphan:

Overall Status
==============

+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| master branch status | |BuildStatus| |Docs| |MITLicense| |CoverageStatus|                                                                                 |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| GitHub status        | |OpenIssues| |OpenPullRequests|                                                                                                    |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+

Driver status
=============

+------------+-----------------------------------+--------------------------+
| NI-DCPower | **Driver Version Tested Against** | 17.6.0                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |nidcpowerLatestVersion| |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |nidcpowerPythonVersion| |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |nidcpowerOpenIssues|    |
+------------+-----------------------------------+--------------------------+
| NI-DMM     | **Driver Version Tested Against** | 17.1.0                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |nidmmLatestVersion|     |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |nidmmPythonVersion|     |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |nidmmOpenIssues|        |
+------------+-----------------------------------+--------------------------+
| NI-FGEN    | **Driver Version Tested Against** | 17.1.0                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |nifgenLatestVersion|    |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |nifgenPythonVersion|    |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |nifgenOpenIssues|       |
+------------+-----------------------------------+--------------------------+
| NI-SCOPE   | **Driver Version Tested Against** | 17.0.2                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |niscopeLatestVersion|   |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |niscopePythonVersion|   |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |niscopeOpenIssues|      |
+------------+-----------------------------------+--------------------------+
| NI-SWITCH  | **Driver Version Tested Against** | 17.0.0                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |niswitchLatestVersion|  |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |niswitchPythonVersion|  |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |niswitchOpenIssues|     |
+------------+-----------------------------------+--------------------------+
| NI-ModInst | **Driver Version Tested Against** | 17.0.0                   |
+------------+-----------------------------------+--------------------------+
|            | **PyPI Version**                  | |nimodinstLatestVersion| |
+------------+-----------------------------------+--------------------------+
|            | **Supported Python Version**      | |nimodinstPythonVersion| |
+------------+-----------------------------------+--------------------------+
|            | **Open Issues**                   | |nimodinstOpenIssues|    |
+------------+-----------------------------------+--------------------------+

===========  ============================================================================================================================
Info         Python bindings for NI Modular Instrument drivers. See `GitHub <https://github.com/ni/nimi-python/>`_ for the latest source.
Author       National Instruments
===========  ============================================================================================================================

.. |BuildStatus| image:: https://img.shields.io/travis/ni/nimi-python.svg
    :alt: Build Status - master branch
    :target: https://travis-ci.org/ni/nimi-python

.. |Docs| image:: https://readthedocs.org/projects/nimi-python/badge/?version=latest
    :alt: Documentation Status - master branch
    :target: https://nimi-python.readthedocs.io/en/latest/?badge=latest

.. |MITLicense| image:: https://img.shields.io/badge/License-MIT-yellow.svg
    :alt: MIT License
    :target: https://opensource.org/licenses/MIT

.. |CoverageStatus| image:: https://coveralls.io/repos/github/ni/nimi-python/badge.svg?branch=master&dummy=no_cache_please_1
    :alt: Test Coverage - master branch
    :target: https://coveralls.io/github/ni/nimi-python?branch=master

.. |nidcpowerLatestVersion| image:: http://img.shields.io/pypi/v/nidcpower.svg
    :alt: Latest NI-DMM Version
    :target: http://pypi.python.org/pypi/nidmm

.. |nidcpowerPythonVersion| image:: http://img.shields.io/pypi/pyversions/nidcpower.svg
    :alt: NI-DCPower supported Python versions
    :target: http://pypi.python.org/pypi/nidcpower

.. |nidmmLatestVersion| image:: http://img.shields.io/pypi/v/nidcpower.svg
    :alt: Latest NI-DCPower Version
    :target: http://pypi.python.org/pypi/nidcpower

.. |nidmmPythonVersion| image:: http://img.shields.io/pypi/pyversions/nidmm.svg
    :alt: NI-DMM supported Python versions
    :target: http://pypi.python.org/pypi/nidmm

.. |nimodinstLatestVersion| image:: http://img.shields.io/pypi/v/nimodinst.svg
    :alt: Latest NI-ModInst Version
    :target: http://pypi.python.org/pypi/nimodinst

.. |nimodinstPythonVersion| image:: http://img.shields.io/pypi/pyversions/nimodinst.svg
    :alt: NI-ModInst supported Python versions
    :target: http://pypi.python.org/pypi/nimodinst

.. |niswitchLatestVersion| image:: http://img.shields.io/pypi/v/niswitch.svg
    :alt: Latest NI-SWITCH Version
    :target: http://pypi.python.org/pypi/niswitch

.. |niswitchPythonVersion| image:: http://img.shields.io/pypi/pyversions/niswitch.svg
    :alt: NI-SWITCH supported Python versions
    :target: http://pypi.python.org/pypi/niswitch

.. |niscopeLatestVersion| image:: http://img.shields.io/pypi/v/niscope.svg
    :alt: Latest NI-SCOPE Version
    :target: http://pypi.python.org/pypi/niscope

.. |niscopePythonVersion| image:: http://img.shields.io/pypi/pyversions/niscope.svg
    :alt: NI-SCOPE supported Python versions
    :target: http://pypi.python.org/pypi/niscope

.. |nifgenLatestVersion| image:: http://img.shields.io/pypi/v/nifgen.svg
    :alt: Latest NI-FGEN Version
    :target: http://pypi.python.org/pypi/nifgen

.. |nifgenPythonVersion| image:: http://img.shields.io/pypi/pyversions/nifgen.svg
    :alt: NI-FGEN supported Python versions
    :target: http://pypi.python.org/pypi/nifgen

.. |OpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues

.. |OpenPullRequests| image:: https://img.shields.io/github/issues-pr/ni/nimi-python.svg
    :alt: Open Pull Requests
    :target: https://github.com/ni/nimi-python/pulls

.. |nidmmOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nidmm.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anidmm

.. |nidcpowerOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nidcpower.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anidcpower

.. |nifgenOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nifgen.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anifgen

.. |niscopeOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/niscope.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Aniscope

.. |niswitchOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nisiwtch.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Aniswitch

.. |nimodinstOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nimodinst.svg
    :alt: Open Issues + Pull Requests
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Animodinst


