name: nimibot_win_32_test

on:
  push: #TBD
    paths-ignore:
      - CHANGELOG.md
      - CONTRIBUTING.md
      - .gitattributes
      - LICENSE
      - VERSION

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  do-the-job:
    name: system_tests_win32
    runs-on: self-hosted # run the job on the newly created runner
    timeout-minutes: 40
    strategy:
      matrix:
        module_name: ["nise"]
    steps:
      - run: |
          whoami
        shell: powershell
      - name: system_tests_win32
        uses: SukruthGrandhiNI/githubactions@master
        with:
          module_name: ${{ matrix.module_name }}
